version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Arantis_portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped