FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy all files
COPY . .

EXPOSE 3000

# Start Next.js in dev mode
CMD ["npm", "run", "dev"]